from decouple import config

DEBUG = config('DEBUG', default=False, cast=bool)
DATABASE_LOCATION = config('DATABASE_LOCATION')
DATABASE_NAME = config('DATABASE_NAME')
SQLALCHEMY_DATABASE_URI = f'{DATABASE_LOCATION}/{DATABASE_NAME}'
SQLALCHEMY_TRACK_MODIFICATIONS = config('SQLALCHEMY_TRACK_MODIFICATIONS', default=False, cast=bool)
SECRET_KEY = config('SECRET_KEY')
DEBUG_TB_INTERCEPT_REDIRECTS = False
